### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by FanManutd** [TimofeySyrov/Toxin#2]
### Кликабельные элементы не должны попадать в выделение
![image](https://user-images.githubusercontent.com/90761929/145370035-690e0229-408a-4ba7-867a-5ac33ee868a6.png)
![image](https://user-images.githubusercontent.com/90761929/145370174-ea9281e1-0a87-4efd-9359-343fe5e6e3e8.png)
### Контент
Стрелка не отцентрована 
![image](https://user-images.githubusercontent.com/90761929/145370791-239db097-ca65-42ee-8641-3b22197ab278.png)
Текст выходит за пределы
![image](https://user-images.githubusercontent.com/90761929/145370905-086b7167-5e07-45af-a397-bcb411cb7330.png)
Что бы не было искажений, можно использовать целочисленные значения, например 8px 
![image](https://user-images.githubusercontent.com/90761929/145371737-11a54d0c-4cdf-456b-aa66-78469bbbff15.png)
### Toggle
Короткое исчезновение можно пофиксить
![2](https://user-images.githubusercontent.com/90761929/145371287-d95ab22c-9ab3-4f57-bdbf-f7ba8cab7e37.gif)
### Text-field
Состояние фокуса в макете выглядит по другому
![image](https://user-images.githubusercontent.com/90761929/145371353-5c893369-a827-47ce-a21e-f76ea16f3583.png)
### Календари и дропдауны должны закрываться по клику за их пределами
![1](https://user-images.githubusercontent.com/90761929/145370454-09627605-2c94-4c39-bdf1-211a5f68c9c8.gif)

**Comment by FanManutd** [comment]
### Header
Не делать выпадающие списки на ховерах. Правило [5.8](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#5.8). Разворачивание по клику более чем достаточно.
![3](https://user-images.githubusercontent.com/90761929/145372933-5511e4cd-e0eb-4cd1-ac5f-e17255eb7bdd.gif)

Элемент меню, который разворачивается, не должен быть ссылкой.

В мобильной версии меню хедера должно сворачиваться в "бургер"
![image](https://user-images.githubusercontent.com/90761929/145373369-5a7c1a28-9275-4a85-9a1c-bb39ef937c16.png)

### Date dropdown
Элементы календаря не круглые
![image](https://user-images.githubusercontent.com/90761929/145374294-77918d9e-14ca-4078-b0a9-071dadb4b3d0.png)
как и в пагинации 
![image](https://user-images.githubusercontent.com/90761929/145374545-79c86f6f-713d-4338-83de-fbd22b1b296f.png)

**Comment by FanManutd** [comment]
### Toggle
Как-то странно ты пофиксил короткое исчезновение кругляша у toggle, путём добавления user-select: none. Наверно ты меня неправильно понял, я имел ввиду не выделение текста, а исчезновения кругляша, когда он переходит справа налево. Обрати внимание, он на миг исчезает и сразу появляется. Если не разберёшься как исправить, могу подсказать. А ещё теперь у toggle пропал cursor: pointer, который должен быть, так как элемент кликабельный.
![3](https://user-images.githubusercontent.com/90761929/146547136-3dbcf187-7b2c-4efe-923c-ecdb2a30d2bc.gif)

### Cursor: pointer
У некликабельных элементов так же не должно быть cursor: pointer. Рейтинг справа readonly, значит ему не нужен cursor: pointer. А ещё у чекбокса пропал cursor: pointer.
![4](https://user-images.githubusercontent.com/90761929/146555255-9e42a8f5-14f5-47ff-b160-6b65784ea59e.gif)


### Dropdown
У дропдауна сейчас есть неочевидное поведение. Например, я ввожу "Взрослые 3" и закрываю дропдаун, не нажимая "применить". Потом снова открываю дропдаун и у пользователя складывается впечатление, как буд-то бы выбрано "взрослые 3", а в инпуте до сих пор спрашивается "Сколько гостей". 
![5](https://user-images.githubusercontent.com/90761929/146548024-c9a047e1-9c55-4207-8c9b-80ab91ddef36.gif)

### Наложение
![image](https://user-images.githubusercontent.com/90761929/146548599-54923cb9-3b00-4658-ae01-c050bc6f3d74.png)

**Comment by TimofeySyrov** [comment]
### Toggle
Я почитал на счет анимации градиентов, как я понял, их нельзя анимировать, поэтому у меня происходит это короткое исчезновение. Если честно не знаю как его пофиксить, попытался сделать наложение активного состояния на неактивное, но получалось слайд-шоу, а не анимация. В итоге просто оставил анимацию только для transform
![image](https://user-images.githubusercontent.com/79060145/146681821-4006875d-53eb-4f8a-b23f-915f3465443b.png)

**Comment by FanManutd** [comment]
> ### Toggle
> Я почитал на счет анимации градиентов, как я понял, их нельзя анимировать, поэтому у меня происходит это короткое исчезновение. Если честно не знаю как его пофиксить, попытался сделать наложение активного состояния на неактивное, но получалось слайд-шоу, а не анимация. В итоге просто оставил анимацию только для transform 

Это можно пофиксить, если псевдоэлементу `after` задать свойство `background: linear-gradient($dark_shade-25, $dark_shade-25)` в твоём случае. То есть что бы переключение происходило не между свойствами `background-color` и `background-image`, а только между `background-image`. 
Напомню, что функцию linear-gradient применяется к свойству `background-image`. Свойство `background` в данном случае просто сокращение.

Если что не критично, можно оставить как сейчас.

**Comment by TimofeySyrov** [comment]
### Toggle

> Это можно пофиксить, если псевдоэлементу after задать свойство background: linear-gradient($dark_shade-25, $dark_shade-25) в твоём случае. То есть что бы переключение происходило не между свойствами background-color и background-image, а только между background-image.
> Напомню, что функцию linear-gradient применяется к свойству background-image. Свойство background в данном случае просто сокращение.
> 
> Если что не критично, можно оставить как сейчас.

Я вроде бы всё сделал так, но все равно не анимируется. Ну ладно, я не против) Раз не критично, то оставим как есть.

![image](https://user-images.githubusercontent.com/79060145/147419744-c618e7a7-a433-456d-9285-75d2816c26dd.png)

![togle](https://user-images.githubusercontent.com/79060145/147419776-c18cba40-d2b5-459d-b601-180c2846e664.gif)

**Comment by FanManutd** [comment]
linear-gradient действительно нельзя анимировать. Там исчезание происходило из-за того, что переключались разные свойства и в момент обратного переключения у background-image элемента after просто не было никакого значения.
