### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by FanManutd** [TimofeySyrov/Toxin#4]
1) Правильно "title"
2) Имя класса с приставкой `js-` не соответствует обычному имени класса dom элемента.
3) Все инклюды должны быть в самом вверху, перед объявлением миксина.
![image](https://user-images.githubusercontent.com/90761929/146554174-20f630db-7f24-4bbc-a8f3-5aaca09991fd.png)

### Неэкранизированная вставка
Есть причина, по которой это используется в проекте? 
![image](https://user-images.githubusercontent.com/90761929/146555028-796a2072-c6c5-4d8f-bbe4-8c2f2e0a6012.png)

**Comment by TimofeySyrov** [comment]
### Неэкранизированная вставка
Я решил везде поставить ! вместо #, потому что с ! можно использовать специальные символы. Например, вот в bullet-list неразрывный пробел
![image](https://user-images.githubusercontent.com/79060145/146688498-d6f10e9f-8ed5-4ce6-bc6b-b20dadd23cfe.png)

**Comment by FanManutd** [comment]
> Имя класса с приставкой js- не соответствует обычному имени класса dom элемента.

![image](https://user-images.githubusercontent.com/90761929/146933139-e5c188ac-63c2-4ad0-a45f-427529bcb611.png)


### Неиспользуемые классы
Полагаю старый код. Такого много во всём проекте. 
![image](https://user-images.githubusercontent.com/90761929/146933452-73f068f4-f6e5-455d-9ddb-a3c0b18d147d.png)

### Тег button
У тега `button` атрибут `type` по умолчанию равен `submit`. Разве эта кнопка должна что-то сабмитить?
![image](https://user-images.githubusercontent.com/90761929/146935830-0830855f-92da-47b6-a451-b09810a69506.png)

### Radio buttons
Зачем помещать компонент с радио кнопками в форму? 
![image](https://user-images.githubusercontent.com/90761929/146936205-c33c9013-b7db-41f8-8cd8-04c1c0800d6e.png)

**Comment by TimofeySyrov** [comment]
### Неиспользуемые классы
> Имя класса с приставкой js- не соответствует обычному имени класса dom элемента.

Пофиксил в ишью [БЭМ #3](https://github.com/TimofeySyrov/Toxin/issues/3). Коммит https://github.com/TimofeySyrov/Toxin/commit/d4115a1a9bb6a96596f567ba22aa1547b1d998b2

**Comment by FanManutd** [comment]
А зачем тут data атрибуты? По моему здесь достаточно дать классы дивам. Тем более, что есть правило - [HTML 2.9](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.9)
![image](https://user-images.githubusercontent.com/90761929/149522116-ac3a755f-1015-4fcf-a677-bebb7c89dbd1.png)
![image](https://user-images.githubusercontent.com/90761929/149522835-c01325ee-a299-4091-8c17-4651d62bad84.png)

А если надо будет использовать слайдер не для цен? 
![image](https://user-images.githubusercontent.com/90761929/149522052-d35b965a-170b-41ab-a5bf-634f0f21099c.png)

**Comment by FanManutd** [comment]
Зачем здесь новый блок?) Если уж делать новый блок в компоненте, то уже как положено, с выносом в отдельную папку и т.д. Но зачем? Сделай это элементом registration card__input

![image](https://user-images.githubusercontent.com/90761929/149827341-e5f885a3-7503-42ce-b9c9-412e5b8f97fb.png)
